%% IQ mixer calibration for 2 channels
data_taking.public.calibration.iqChnl(...
        'awgName','da_ustc_1','chnlSet','b05_2_1','maxSbFreq',200e6,'sbFreqStep',20e6,...
			'loFreqStart',4.5e9,'loFreqStop',6.5e9,'loFreqStep',100e6,'spcAvgNum',1,...
          'notes','DAC B05, I:CH2, Q CH1','gui',true,'save',true);