#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 31 22:36:57 2017

@author: chen
"""
from qutip import *
import numpy as np
import matplotlib.pyplot as plt 
from pylab import *

print('start')
pi = np.pi
wc = 7.0  * 2 * pi  # cavity frequency
wa1 = 5.0  * 2 * pi  # atom frequency
wa2 = 6.0  * 2 * pi  # atom frequency
g1  = 0.1 * 2 * pi  # coupling strength
g2  = 0.1 * 2 * pi  # coupling strength
delta1 = wa1-wc
delta2 = wa2-wc

N = 3              # number of cavity fock states
n = 0               # number of photon
level = 2

sm1 = tensor( destroy(level), qeye(level))
sm2 = tensor(qeye(level), destroy(level))
sz1 = tensor( sigmaz(), qeye(level))
sz2 = tensor(qeye(level), sigmaz())
#H1 = wa1 * sm1.dag() * sm1 + wa2 * sm2.dag() * sm2 + 0.5*g1*g2*(delta1+delta2)/(delta1*delta2)*(sm1 + sm1.dag())*(sm2 + sm2.dag())
H1 = wa1 * sm1.dag() * sm1 + wa2 * sm2.dag() * sm2 + g1*(sm1 + sm1.dag())*(sm2 + sm2.dag())
H1 = -wa1 * sz1/2 - wa2 * sz2/2 + g1*(sm1 + sm1.dag())*(sm2 + sm2.dag())
w = H1.eigenenergies()
print(w[2]-w[0],w[3]-w[1])