params:
    # 参数格式 [min, max, step]
    - Cj: [0, 1, 0.1]
    - Cd: [0, 1, 0.1]
    - Ci: [0, 1, 0.1]
    - Rj: [0, 1, 0.1]
    - Ri: [0, 1, 0.1]
    - Rs: [0, 1, 0.1]
    - Ls: [0, 1, 0.1]
    - Cp: [0, 1, 0.1]

population_capacity:
    # 种群容量，一般取为20~100
    50

epochs:
    # 进化代数，一般取为100~500
    100

pc:
    # 交叉概率，一般取为0.4~0.99
    0.9
    
px:
    # 变异概率，一般取为0.0001~0.1
    0.01
    