function CData = DoubleArrow()
    %

% Copyright 2015 Yulin Wu, Institute of Physics, Chinese  Academy of Sciences
% mail4ywu@gmail.com/mail4ywu@icloud.com

    CData(:,:,1) = [...
        0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN     0     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN     0     0     0     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN   NaN     0     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN   NaN     0     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN   NaN   NaN     0     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN   NaN   NaN     0   NaN   NaN     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0   NaN   NaN     0   NaN   NaN   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0     0   NaN   NaN   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0     0   NaN   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0     0   NaN   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0     0     0     0   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0     0   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0;...
    ];

CData(:,:,2) = [...
     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN     0     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN     0     0     0     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN   NaN     0     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN   NaN     0     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN   NaN   NaN     0     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN   NaN   NaN     0   NaN   NaN     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0   NaN   NaN     0   NaN   NaN   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0     0   NaN   NaN   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0     0   NaN   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0     0   NaN   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0     0     0     0   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0     0   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0;...
    ];

CData(:,:,3) = [...
     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN     0     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN     0     0     0     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN   NaN     0     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN   NaN     0     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN   NaN   NaN     0     0     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN   NaN   NaN     0   NaN   NaN     0     0     0   NaN   NaN   NaN   NaN   NaN   NaN   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0   NaN   NaN     0   NaN   NaN   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0     0   NaN   NaN   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0     0   NaN   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0     0   NaN   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0     0     0     0   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0     0   NaN;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0     0     0;...
   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0     0;...
    ];
end